export const marketData = [
  { game: "Warriors @ Lakers", league: "NBA", confidence: 89, odds: "-4.5 (-110)", score: 89, ev: "+9.2%", signal: "Sharp Money", movement: "+1.5", type: 'green' },
  { game: "Bills @ Chiefs", league: "NFL", confidence: 90, odds: "-4.5 (-110)", score: 89, ev: "+9.2%", signal: "Market Support", movement: "+1.5", type: 'blue' },
  { game: "Red Sox @ Yankees", league: "MLB", confidence: 40, odds: "-4.5 (-110)", score: 54, ev: "-5.2%", signal: "Market Resistance", movement: "+1.5", type: 'red' },
  { game: "Celtics @ 76ers", league: "NBA", confidence: 75, odds: "-2.5 (-105)", score: 82, ev: "+4.5%", signal: "Sharp Money", movement: "+0.5", type: 'green' },
  { game: "Eagles @ Cowboys", league: "NFL", confidence: 88, odds: "+3.0 (-115)", score: 85, ev: "+7.8%", signal: "Market Support", movement: "-1.0", type: 'blue' },
  { game: "Dodgers @ Giants", league: "MLB", confidence: 65, odds: "-140", score: 72, ev: "+2.1%", signal: "Public Money", movement: "+10", type: 'green' },
  { game: "Bruins @ Maple Leafs", league: "NHL", confidence: 55, odds: "-1.5 (+150)", score: 68, ev: "+1.2%", signal: "Market Support", movement: "+0.5", type: 'blue' },
  { game: "Real Madrid @ Barcelona", league: "Soccer", confidence: 92, odds: "+110", score: 94, ev: "+11.5%", signal: "Sharp Money", movement: "+0.25", type: 'green' },
  { game: "Bucks @ Heat", league: "NBA", confidence: 35, odds: "+5.5 (-110)", score: 45, ev: "-3.4%", signal: "Market Resistance", movement: "+1.0", type: 'red' },
  { game: "Bengals @ Ravens", league: "NFL", confidence: 82, odds: "-6.5 (-110)", score: 78, ev: "+5.6%", signal: "Sharp Money", movement: "+0.5", type: 'green' },
  { game: "Astros @ Rangers", league: "MLB", confidence: 70, odds: "-125", score: 75, ev: "+3.2%", signal: "Public Money", movement: "-5", type: 'blue' },
  { game: "Rangers @ Devils", league: "NHL", confidence: 48, odds: "+120", score: 52, ev: "-1.5%", signal: "Market Resistance", movement: "0.0", type: 'red' },
  { game: "Man City @ Liverpool", league: "Soccer", confidence: 85, odds: "-120", score: 88, ev: "+6.7%", signal: "Sharp Money", movement: "-0.5", type: 'green' },
  { game: "Suns @ Nuggets", league: "NBA", confidence: 78, odds: "-1.5 (-110)", score: 80, ev: "+5.1%", signal: "Market Support", movement: "+1.0", type: 'blue' },
  { game: "Jets @ Dolphins", league: "NFL", confidence: 25, odds: "+10.5 (-110)", score: 32, ev: "-8.9%", signal: "Market Resistance", movement: "+2.0", type: 'red' },
  { game: "Braves @ Mets", league: "MLB", confidence: 91, odds: "-165", score: 92, ev: "+10.2%", signal: "Sharp Money", movement: "-15", type: 'green' },
  { game: "Avalanche @ Stars", league: "NHL", confidence: 62, odds: "-110", score: 65, ev: "+2.5%", signal: "Public Money", movement: "+0.5", type: 'blue' },
  { game: "Bayern Munich @ Dortmund", league: "Soccer", confidence: 80, odds: "-145", score: 83, ev: "+5.9%", signal: "Sharp Money", movement: "-0.75", type: 'green' },
  { game: "Knicks @ Cavaliers", league: "NBA", confidence: 42, odds: "+4.5 (-105)", score: 48, ev: "-4.2%", signal: "Market Resistance", movement: "-0.5", type: 'red' },
  { game: "49ers @ Seahawks", league: "NFL", confidence: 86, odds: "-3.5 (-110)", score: 84, ev: "+7.1%", signal: "Sharp Money", movement: "+1.5", type: 'green' },
  { game: "Blue Jays @ Orioles", league: "MLB", confidence: 58, odds: "+115", score: 62, ev: "+0.8%", signal: "Public Money", movement: "+5", type: 'blue' },
  { game: "Golden Knights @ Oilers", league: "NHL", confidence: 74, odds: "-125", score: 77, ev: "+4.8%", signal: "Sharp Money", movement: "-1.0", type: 'green' },
  { game: "Arsenal @ Chelsea", league: "Soccer", confidence: 68, odds: "+150", score: 71, ev: "+3.5%", signal: "Market Support", movement: "+0.25", type: 'blue' },
];
